server:
  port: 8081
#hibernate.current_session_context_class
spring:
  application:
    name: springboot-batch
  datasource:
    url: jdbc:mysql://localhost:3306/batch?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  batch:
    # 在项目启动时进行执行建表sql
    initialize-schema: always
    job:
      enabled: false
      names: parentjob
    table-prefix: batch_

    datasource:
      # 项目启动时的建表sql脚本,该脚本由Spring Batch提供
      schema: classpath:/org/springframework/batch/core/schema-mysql.sql

#spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
  ##----------------------JPA-----------------------------
  mybatis:
    mapper-locations: classpath:/mapper/*Mapper.xml
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        #current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    show-sql: true
    database: mysql
